# Generated by Django 5.1.4 on 2025-01-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_animal_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('motivo_doacao', models.TextField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais', to='animais.tutoratual'),
        ),
    ]
