# Generated by Django 5.1.4 on 2025-01-09 16:30

import animais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_tutoratual_animal_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='idade',
        ),
        migrations.AddField(
            model_name='animal',
            name='idade_em_meses',
            field=models.IntegerField(default=0, validators=[animais.models.validar_idade_em_meses]),
        ),
    ]
