# Generated by Django 5.1.4 on 2025-01-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0004_remove_animal_idade_animal_idade_em_meses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='TutorAtual',
        ),
    ]
